Added Square Sense, Paris, France
poteto/hiring-without-whiteboards pull request #1024
Opened 2020-10-12 07:27 UTC by candidtim

## Add/Update/Remove Square Sense

- [x] I have read the [contributing guidelines](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md)
- [x] I agree to the [Code of Conduct](https://github.com/poteto/hiring-without-whiteboards/blob/master/CODE_OF_CONDUCT.md)
- [x] I have followed the [format](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md#format) prescribed in the contributing guidelines
- [ ] (OPTIONAL) In your pull request message, add additional context on the interview process if necessary

2020-10-13 18:07 UTC, poteto requested changes

2020-10-13 18:35 UTC, candidtim commented on README.md
> +- [Square Sense](https://www.welcometothejungle.com/fr/companies/square-sense) | Paris, France | Short phone screen to confirm the interest, take-home project (similar to some of our existing softwar
OK, done.

2020-10-24 07:30 UTC, poteto approved these changes

2020-10-24 07:31 UTC, poteto commented
bors r+

2020-10-24 07:32 UTC, merged