Adding btw.so to the list
poteto/hiring-without-whiteboards pull request #1089
Opened 2021-06-07 06:57 UTC by siddug

## Add/Update/Remove <CompanyName>

- [x] I have read the [contributing guidelines](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md)
- [x] I agree to the [Code of Conduct](https://github.com/poteto/hiring-without-whiteboards/blob/master/CODE_OF_CONDUCT.md)
- [x] I have followed the [format](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md#format) prescribed in the contributing guidelines
- [ ] (OPTIONAL) In your pull request message, add additional context on the interview process if necessary

2021-06-09 06:08 UTC, SwapnilSoni1999 commented
It seems this site doesnt have any recruitment or hiring section. How to apply?

2021-06-09 16:52 UTC, poteto requested changes

2021-06-09 16:52 UTC, poteto commented on README.md
> +- [btw](https://www.btw.so) | Remote/ Singapore, Singapore / Bangalore, India | The open source platform to understand, engage and convert your visitors into customers
This should be a description of the interview process.

2021-06-11 06:46 UTC, siddug commented on README.md
> +- [btw](https://www.btw.so) | Remote/ Singapore, Singapore / Bangalore, India | The open source platform to understand, engage and convert your visitors into customers
Thanks for the comment. It is updated now :)

2021-06-12 11:22 UTC, siddug commented
Have updated the commit with the requested changes. Thanks @poteto

@SwapnilSoni1999 Do check the open roles here - https://angel.co/company/btw-2/jobs (Please do refer if you think anyone fits)

2021-06-14 16:22 UTC, poteto approved these changes

2021-06-14 16:22 UTC, poteto commented
Thanks!

bors r+

2021-06-14 16:24 UTC, merged