Add Flower Labs
poteto/hiring-without-whiteboards pull request #1358
Opened 2023-08-22 16:38 UTC by jafermarq

## Add/Update/Remove <CompanyName>

- [ ] I have read the [contributing guidelines](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md)
- [ ] I agree to the [Code of Conduct](https://github.com/poteto/hiring-without-whiteboards/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have followed the [format](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md#format) prescribed in the contributing guidelines
- [ ] (OPTIONAL) In your pull request message, add additional context on the interview process if necessary

2023-08-25 15:47 UTC, poteto commented
bors r+

2023-08-28 10:18 UTC, jafermarq commented
Hi @poteto , I checked the bors log and found two warnings. I fixed the one about trailing `/`. Not sure what to do about the `Remote in Europe` warning. Do you have any suggestions? I think these two warning caused the build to fail?

2023-09-06 18:20 UTC, poteto requested changes

2023-09-06 18:20 UTC, poteto commented on README.md
> +- [Flower Labs](https://flower.dev) | Cambridge, UK / Berlin, Germany / Remote in Europe. Reach out to us by email or on Slack with your CV. You'll receive a written interview which should take 15min
```suggestion
- [Flower Labs](https://flower.dev) | Cambridge, UK; Berlin, Germany; Remote | Reach out to us by email or on Slack with your CV. You'll receive a written interview which should take 15min to 30min to complete, after which we'll schedule at most 2x technical video interviews with a potential take-home assignment in between. Alternatively, you share the Open-Source code you have written so we can discuss that.
```

2023-09-06 18:20 UTC, poteto commented on README.md
> +- [Flower Labs](https://flower.dev) | Cambridge, UK / Berlin, Germany / Remote in Europe. Reach out to us by email or on Slack with your CV. You'll receive a written interview which should take 15min
This should work, our linter isn't super smart. In particular we only allow "Remote" as a location, but if you have a jobs page you could mention there that remote is limited to similar timezones

2023-09-06 18:50 UTC, jafermarq commented on README.md
> +- [Flower Labs](https://flower.dev) | Cambridge, UK / Berlin, Germany / Remote in Europe. Reach out to us by email or on Slack with your CV. You'll receive a written interview which should take 15min
Happy to leave it as "remote"

2023-09-06 19:12 UTC, poteto commented
Thanks!

bors r+

2023-09-06 19:13 UTC, merged